version: 0.0
os: linux 

files:
  - source: /
    destination: /home/ubuntu
hooks:
  install:
    runtime-versions:
      nodejs: 21
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
