version: 0.2

phases:
  install:
    runtime-version:
    nodejs: 21
  pre_build:    
    commands:
      - echo Installing source node dependencies...
      - npm install
  build:
    commands:
      - echo Build started on date
      - echo Compiling the node code
  post_build:
    commands:
      - echo Build completed on date
artifacts:
  files:
    - '**/*'
  base-directory: base_location
  name: artifact
  discard-paths: no
